image:
  repository: ghcr.io/o11ylite/o11ylite
  pullPolicy: IfNotPresent
  # Defaults to .Chart.AppVersion if not set
  tag: ""

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: false
  size: 10Gi
  # storageClass: ""

resources: {}
  # limits:
  #   cpu: "2"
  #   memory: 4Gi
  # requests:
  #   cpu: "1"
  #   memory: 2Gi

env: []
  # - name: O11YLITE_DATA_PATH
  #   value: /data
