#!/usr/bin/env bash
set -euo pipefail

VERSION="$(buildkite-agent meta-data get "release-version")"
TAG="$VERSION"

echo "--- :git: Configuring HTTPS authentication"
git config url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "git@github.com:"

echo "--- :git: Tagging $TAG"
git tag "$TAG"
git push origin "$TAG"

echo "--- :github: Creating GitHub release"
IMAGE="ghcr.io/o11ylite/o11ylite"
gh release create "$TAG" --title "$TAG" --generate-notes --notes "## Docker image

\`\`\`
docker pull $IMAGE:$VERSION
\`\`\`
"
